# render.yaml (for Render)
services:
  - type: web
    name: binance-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: "/health"
